# -*- coding: utf-8 -*-
"""Assigment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lPqH0jrVaohy-fd8H0p3BSiUTcq4xXLx
"""

import os
HOME = os.getcwd()
print(HOME)

!pip install ultralytics

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO
from IPython.display import display, Image

#!mkdir {HOME}/datasets
#%cd {HOME}/datasets

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="0v0beAZlQEiGhgXI7uz5")
project = rf.workspace("hvac-hbzel").project("hvac_8_class-lfhrn")
version = project.version(1)
dataset = version.download("yolov11")

!yolo task=detect mode=train model=yolo11s.pt data=/content/HVAC_8_CLASS-1/data.yaml epochs=100 imgsz=640 plots=True

# Carga el archivo best.pt de la carpeta runs
model = YOLO("/content/runs/detect/train/weights/best.pt")
# Export the model to NCNN format
model.export(format="ncnn", imgsz=640)

# Zip the project
!zip -r hvac_project.zip HVAC_8_CLASS-1 runs
# Then download
from google.colab import files
files.download("hvac_project.zip")

"""#UPLOAD SOME VIDEOS TO TEST HERE"""

# I uploaded one video to path /content/VID-20250916-WA0004.mp4
!yolo detect predict model=runs/detect/train/weights/best.pt source=/content/VID-20250916-WA0004.mp4 conf=0.5 save=True