# -*- coding: utf-8 -*-
"""Assigment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lPqH0jrVaohy-fd8H0p3BSiUTcq4xXLx
"""

!pip install ultralytics

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO
from IPython.display import display, Image

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="0v0beAZlQEiGhgXI7uz5")
project = rf.workspace("hvac-hbzel").project("hvac_8_class-lfhrn")
version = project.version(4)
dataset = version.download("yolov11")

!yolo task=detect mode=train model=yolo11s.pt data=/content/HVAC_8_CLASS-4/data.yaml epochs=100 imgsz=640 plots=True

# Load best.pt frile from runs folder
model = YOLO("/content/runs/detect/train/weights/best.pt")
# Export the model to NCNN format (might be helpful)
model.export(format="ncnn", imgsz=640)

# Also we can use quantization (int8) for Google Coral TPU for example
model.export(format="edgetpu", imgsz=640)
# I don't have an Nvidia graphic card but I do count with an Intel Iris Xe
model.export(format="openvino",imgsz=640)

# Zip the project
!zip -r hvac_project_small.zip HVAC_8_CLASS-1 runs
# Good to go!
from google.colab import files
files.download("hvac_project_small.zip")

"""#UPLOAD SOME VIDEOS TO TEST HERE"""

# I uploaded one video to path /content/VID-20250916-WA0004.mp4
!yolo detect predict model=runs/detect/train/weights/best.pt source=/content/VID-20250916-WA0004.mp4 conf=0.5 save=True